#!/bin/bash
coin=$1
wallet=$2
worker=$3
thread=$4

if [[ $coin == "scala" ]]
then
  wget https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-linux-x86_64.zip && apt install -y unzip && unzip XLArig-v5.2.2-linux-x86_64.zip && ./xlarig -o scala.herominers.com:10131 -u  $wallet+15000 -p $worker -k -a panthera -t$thread --randomx-1gb-pages
elif [[ $coin == "verus" ]]
then
  wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz && tar xf nheqminer-Linux-v0.8.2.tgz && tar xf nheqminer-Linux-v0.8.2.tar.gz && cd nheqminer && ./nheqminer -v -l na.luckpool.net:3956 -u $wallet.$worker -p $worker -t $thread
elif [[ $coin == "win" ]]
then
  wget https://github.com/xmrig/xmrig/releases/download/v6.12.0/xmrig-6.12.0-bionic-x64.tar.gz && tar xf xmrig-6.12.0-bionic-x64.tar.gz && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u WBTC:$wallet.$worker -t$thread
elif [[ $coin == "turtlecoin" ]]
then
  wget https://github.com/xmrig/xmrig/releases/download/v6.12.0/xmrig-6.12.0-bionic-x64.tar.gz && tar xf xmrig-6.12.0-bionic-x64.tar.gz && ./xmrig --donate-level 1 -o turtlecoin.herominers.com:10381 -u $wallet -p $worker -a argon2/chukwav2 -k -t$thread
else
  echo "nothing"
fi

